# Generated by Django 3.1 on 2021-04-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0002_auto_20210411_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('datePickUp', models.DateField(null=True, verbose_name='Дата принятия')),
                ('pet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shelter.pet')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shelter.profile')),
            ],
        ),
    ]
