# Generated by Django 3.1 on 2021-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datePickUp',
            field=models.DateField(blank=True, null=True, verbose_name='Дата принятия'),
        ),
    ]
