# Generated by Django 3.1 on 2021-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0005_auto_20210415_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerapplication',
            name='address_shelter',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес приюта'),
        ),
        migrations.AddField(
            model_name='ownerapplication',
            name='description_shelter',
            field=models.TextField(blank=True, default='', verbose_name='Описание приюта'),
        ),
        migrations.AddField(
            model_name='ownerapplication',
            name='title_shelter',
            field=models.CharField(default='', max_length=200, verbose_name='Название приюта'),
        ),
    ]
