# Generated by Django 3.1 on 2021-04-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0006_auto_20210419_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sent', 'отправлена'), ('accepted', 'принята'), ('rejected', 'отклонена'), ('confirmed', 'подтверждена')], default='sent', max_length=15, verbose_name='Статус'),
        ),
    ]
