# Generated by Django 3.1 on 2021-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateViewing',
            field=models.DateField(blank=True, null=True, verbose_name='Дата росмотра животного'),
        ),
    ]
