# Generated by Django 3.1 on 2021-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0009_auto_20210506_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerapplication',
            name='status',
            field=models.CharField(choices=[('accepted', 'принята'), ('sent', 'отправлена')], default='sent', max_length=15, verbose_name='Статус'),
        ),
    ]
