# Generated by Django 3.1 on 2021-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0010_ownerapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateViewing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата просмотра животного'),
        ),
    ]
