# Generated by Django 3.1 on 2021-05-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0011_auto_20210508_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('dateCreate', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Shelter.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shelter.profile', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shelter.report'),
        ),
    ]
