# Generated by Django 3.1 on 2021-05-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0012_auto_20210509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(verbose_name='Отчет'),
        ),
    ]
