# Generated by Django 3.1 on 2021-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0014_news_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vector',
            field=models.TextField(blank=True, default='', verbose_name='Вектор'),
        ),
    ]
